const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'UPDATE_COLLECTIONS',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTION_FAILURE'
}
export default ShopActionTypes